#!/usr/bin/env bash
set -e

# Caminho para o binário do Go
BIN_PATH="./cli-command"

# Verifique se o binário existe e é executável
if [ ! -x "$BIN_PATH" ]; then
  echo "O binário do Go não foi encontrado ou não é executável: $BIN_PATH" >&2
  exit 1
fi

$BIN_PATH "$@"
