name: Go CI

on:
  push:
    branches:
      - main
      - "**/feature/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy

      - name: Install scc from source
        run: |
          echo "Cloning scc repository..."
          git clone https://github.com/boyter/scc.git || { echo "Clone failed"; exit 1; }
          cd scc
          echo "Building scc..."
          go build -o scc || { echo "Build failed"; exit 1; }
          echo "Moving scc to /usr/local/bin"
          sudo mv scc /usr/local/bin/scc

      # - name: Run tests
      # run: go test -v ./...

      - name: Install Lint Package
        run: go get golang.org/x/lint/golint

      - name: Build
        run: go build -v ./...

      - name: Lint
        run: go run golang.org/x/lint/golint ./...

      - name: Check formatting
        run: gofmt -s -l .

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            **/go.sum
            **/go.mod
            ${{ github.workspace }}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Publish
        env:
          GOPROXY: https://proxy.golang.org
          GOPRIVATE: github.com/pqdluiz/cli-command
        run: |
          go install ./...
          go list -m github.com/pqdluiz/cli-command
          go clean -modcache
